In [4]:
# Download specific file from Kaggle dataset
import kagglehub
import pandas as pd

# Download only the specific CSV file
path = kagglehub.dataset_download(
    "subhamjain/health-dataset-complete-singapore",
    path="weekly-infectious-disease-bulletin-cases/weekly-infectious-disease-bulletin-cases.csv"
)

print("Downloaded file path:", path)

# Load the CSV file
df = pd.read_csv(path)

print("\nFirst 5 records:")
print(df.head())

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.2).
Downloaded file path: /Users/qytay/.cache/kagglehub/datasets/subhamjain/health-dataset-complete-singapore/versions/1/weekly-infectious-disease-bulletin-cases/weekly-infectious-disease-bulletin-cases.csv

First 5 records:
   epi_week                  disease  no._of_cases
0  2012-W01  Acute Viral hepatitis B             0
1  2012-W01  Acute Viral hepatitis C             0
2  2012-W01          Avian Influenza             0
3  2012-W01   Campylobacterenterosis             6
4  2012-W01        Chikungunya Fever             0

In [7]:
df.shape

(16066, 3)

In [5]:
df.to_csv("weekly-infectious-disease-bulletin-cases.csv", index=False)

# Checking Demographic data file

In [13]:
residenti = pd.read_csv("hsetod2025.csv")
residenti.rename(columns={"PA": "Planning Area", "SZ" : "Subzone", "TOD" : "Type of Dwelling", "HSE":"Dwelling Count"}, inplace=True)
residenti

,Planning Area,Subzone,Type of Dwelling,Dwelling Count,Time
0,Ang Mo Kio,Ang Mo Kio Town Centre,HDB 1- and 2-Room Flats,0,2025
1,Ang Mo Kio,Ang Mo Kio Town Centre,HDB 3-Room Flats,170,2025
2,Ang Mo Kio,Ang Mo Kio Town Centre,HDB 4-Room Flats,220,2025
3,Ang Mo Kio,Ang Mo Kio Town Centre,HDB 5-Room and Executive Flats,580,2025
4,Ang Mo Kio,Ang Mo Kio Town Centre,HUDC Flats (excluding those privatised),0,2025
...,...,...,...,...,...
2651,Yishun,Yishun West,HDB 5-Room and Executive Flats,1730,2025
2652,Yishun,Yishun West,HUDC Flats (excluding those privatised),0,2025
2653,Yishun,Yishun West,Landed Properties,0,2025
2654,Yishun,Yishun West,Condominiums and Other Apartments,2140,2025
2655,Yishun,Yishun West,Others,250,2025

In [14]:
residenti.to_csv("hsetod2025_renamed.csv", index=False)

In [12]:
pd.read_csv("Notes_hsetod2025.csv", encoding='latin1')

   Notes for Residential Dwellings by Planning Area/Subzone and Type of Dwelling, June 2025
0                                     Column Headers:
1                                  PA - Planning Area
2                                        SZ - Subzone
3                             TOD - Type of Dwelling
4                                Hse - Dwelling Count
5                                Time - Time / Period
6                                               Note:
7   1) For June 2025, Planning Areas refer to area...
8   2) Data are based on the Singapore Standard Cl...
9   3) The figures have been rounded to the neares...
10        4) The data may not add up due to rounding.
11                                    Date generated:
12                                          29/9/2025
13                                            Source:
14                 Singapore Department of Statistics

In [ ]:
data_2025 = pd.read_csv("respopagesex2025.csv")
data_2024 = pd.read_csv("respopagesex2024.csv")
data_2023 = pd.read_csv("respopagesex2023.csv")
data_2022 = pd.read_csv("respopagesex2022.csv")

dfs = [data_2025, data_2024, data_2023, data_2022]

merged = None
for df in dfs:
    df.rename(columns={"PA": "Planning Area", "SZ" : "Subzone", "Pop" : "Resident Count"}, inplace=True)
    if merged is None:
        merged = df
    else:
        merged = pd.concat([merged, df], ignore_index=True)

In [24]:
pd.read_csv("Notes_respopagesex2025.csv").iloc[10,:]

Notes for Singapore Residents by Planning Area/Subzone, Single Year of Age and Sex, June 2025    3) The figures have been rounded to the neares...
Name: 10, dtype: object

In [32]:
merged['Resident Count'] = merged['Resident Count'].astype(str).str.extract('(\d+)').astype(int)

In [33]:
merged.dtypes

Planning Area     object
Subzone           object
Age               object
Sex               object
Resident Count     int64
Time               int64
dtype: object

In [37]:
merged.shape

(241696, 6)

In [35]:
merged.groupby(["Time", "Subzone"])["Resident Count"].sum()

Time  Subzone
2022  Admiralty          13760
      Airport Road           0
      Alexandra Hill     13430
      Alexandra North     2900
      Aljunied           41350
                         ...
2025  Yishun South       41020
      Yishun West        50760
      Yuhua East         23190
      Yuhua West         18270
      Yunnan             65460
Name: Resident Count, Length: 1328, dtype: int64

In [36]:
merged.to_csv("Singapore_residents_by_planning_area_2022_2025_renamed.csv", index=False)

In [19]:
data.to_csv("Singapore_residents_by_planning_area.csv", index=False)

In [20]:
data.shape

(60424, 6)

# COVID - 19 DATA SET

In [38]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "covid19_sg.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "shivamb/covid19-in-singapore-latest-detailed-data",
  file_path,
  # Provide any additional arguments like 
  # sql_query or pandas_kwargs. See the 
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

print("First 5 records:", df.head())

/var/folders/b6/93kc4vbd30b195px6g6lqtjc0000gn/T/ipykernel_4371/3186058505.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (0.4.2).
Downloading from https://www.kaggle.com/api/v1/datasets/download/shivamb/covid19-in-singapore-latest-detailed-data?dataset_version_number=122&file_name=covid19_sg.csv...

100%|██████████| 81.1k/81.1k [00:00<00:00, 430kB/s]

First 5 records:          Date  Daily Confirmed  False Positives Found  Cumulative Confirmed  \
0  2020-01-23                1                    NaN                     1
1  2020-01-24                2                    NaN                     3
2  2020-01-25                1                    NaN                     4
3  2020-01-26                0                    NaN                     4
4  2020-01-27                1                    NaN                     5

   Daily Discharged  Passed but not due to COVID  Cumulative Discharged  \
0                 0                            0                      0
1                 0                            0                      0
2                 0                            0                      0
3                 0                            0                      0
4                 0                            0                      0

   Discharged to Isolation  Still Hospitalised  Daily Deaths  ...  \
0                        0                   1             0  ...
1                        0                   3             0  ...
2                        0                   4             0  ...
3                        0                   4             0  ...
4                        0                   5             0  ...

   Cumulative Individuals Vaccinated  \
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN

   Cumulative Individuals Vaccination Completed  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN

   Perc population completed at least one dose  \
0                                          NaN
1                                          NaN
2                                          NaN
3                                          NaN
4                                          NaN

   Perc population completed vaccination  Sinovac vaccine doses  \
0                                    NaN                    NaN
1                                    NaN                    NaN
2                                    NaN                    NaN
3                                    NaN                    NaN
4                                    NaN                    NaN

   Cumulative individuals using Sinovac vaccine  \
0                                           NaN
1                                           NaN
2                                           NaN
3                                           NaN
4                                           NaN

   Doses of other vaccines recognised by WHO  \
0                                        NaN
1                                        NaN
2                                        NaN
3                                        NaN
4                                        NaN

   Cumulative individuals using other vaccines recognised by WHO  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

   Number taken booster shots  Perc population taken booster shots
0                         NaN                                  NaN
1                         NaN                                  NaN
2                         NaN                                  NaN
3                         NaN                                  NaN
4                         NaN                                  NaN

[5 rows x 36 columns]

In [45]:
df.columns

Index(['Date', 'Daily Confirmed', 'False Positives Found',
       'Cumulative Confirmed', 'Daily Discharged',
       'Passed but not due to COVID', 'Cumulative Discharged',
       'Discharged to Isolation', 'Still Hospitalised', 'Daily Deaths',
       'Cumulative Deaths', 'Tested positive demise', 'Daily Imported',
       'Daily Local transmission', 'Local cases residing in dorms MOH report',
       'Local cases not residing in doms MOH report',
       'Intensive Care Unit (ICU)', 'General Wards MOH report',
       'In Isolation MOH report', 'Total Completed Isolation MOH report',
       'Total Hospital Discharged MOH report',
       'Requires Oxygen Supplementation or Unstable', 'Linked community cases',
       'Unlinked community cases', 'Phase', 'Cumulative Vaccine Doses',
       'Cumulative Individuals Vaccinated',
       'Cumulative Individuals Vaccination Completed',
       'Perc population completed at least one dose',
       'Perc population completed vaccination', 'Sinovac vaccine doses',
       'Cumulative individuals using Sinovac vaccine',
       'Doses of other vaccines recognised by WHO',
       'Cumulative individuals using other vaccines recognised by WHO',
       'Number taken booster shots', 'Perc population taken booster shots'],
      dtype='object')

In [42]:
df.Date.min()

'2020-01-23'

In [43]:
df.to_csv("covid19_sg_2020_to_2022.csv", index=False)